export const duckParagraphs = [
  "Ducks are amazing waterfowl creatures.",
  "Mallard ducks have green, shiny heads.",
  "Ducklings are cute and fluffy.",
  "Ducks quack loudly at dawn.",
  "Ducks swim gracefully in ponds.",
  "Ducks' feathers are waterproof naturally.",
  "Ducks eat plants and small insects.",
  "Drake is a male duck.",
  "Female ducks are called hens.",
  "Ducks migrate during winter season.",
  "Wood ducks nest in trees.",
  "Ducks have webbed feet.",
  "Ducks preen their feathers often.",
  "Ducks communicate using various sounds.",
  "Ducks can dive underwater easily.",
  "Ducks have excellent vision abilities.",
  "Ducks enjoy socializing in flocks.",
  "Ducks can fly long distances.",
  "Ducks are found worldwide, everywhere.",
  "Some ducks are excellent divers.",
  "Duck eggs are nutritious and delicious.",
  "Ducks are symbols of fidelity.",
  "Mandarin ducks are incredibly colorful.",
  "Ducks can live in parks.",
  "Ducks adapt well to captivity.",
  "Ducks help control insect populations.",
  "Duck down is very warm.",
  "Teal ducks are small, fast.",
  "Eider ducks provide luxurious down.",
  "Pekin ducks are domestic breed.",
  "Ducks have distinctive flight patterns.",
  "Muscovy ducks have unique red faces.",
  "Ducks are part of folklore.",
  "Northern pintails have elegant necks.",
  "Ducks have high metabolic rates.",
  "Ducks often mate for life.",
  "Ducks nest near water bodies.",
  "Canvasback ducks have sloping profiles.",
  "Ducks forage for food diligently.",
  "Ducks play important ecological roles.",
  "Ducks are popular in zoos.",
  "Ducks can be very friendly.",
  "Ducks' quacks echo in canyons.",
  "Ducks flap wings to communicate.",
  "Ducks can walk on ice.",
  "Ducks rest on one leg.",
  "Ducks' bills are highly sensitive.",
  "Ducks paddle smoothly through water.",
  "Ducks can see in color.",
  "Duck hunting is regulated carefully.",
  "Ducks preen to stay clean.",
  "Duck calls are used in hunting.",
  "Ducks can sleep while floating.",
  "Ducks' plumage varies by species.",
  "Duck ponds are serene places.",
  "Ducks are featured in stories.",
  "Ducks waddle endearingly on land.",
  "Ducks' nests are well hidden.",
  "Ducks have strong maternal instincts.",
  "Ducks are curious by nature.",
  "Ducks enjoy rain showers immensely.",
  "Ducks are very photogenic birds.",
  "Ducks' bones are lightweight for flying.",
  "Ducks can turn on water.",
  "Ducks' eyes adjust underwater quickly.",
  "Ducks' webbed feet aid swimming.",
  "Ducks' feathers trap insulating air.",
  "Ducks' diet includes grains often.",
  "Ducks rest in shaded areas.",
  "Ducks' migration patterns are studied.",
  "Ducks' beaks are multifunctional tools.",
  "Ducks are drawn to wetlands.",
  "Ducks' down feathers are prized.",
  "Ducks' quacks can be loud.",
  "Ducks' offspring follow their mothers.",
  "Ducks molt their feathers annually.",
  "Ducks' wing spans vary greatly.",
  "Ducks' feet leave unique prints.",
  "Ducks' eyes are positioned laterally.",
  "Ducks contribute to biodiversity significantly.",
  "Ducks' vocalizations vary by species.",
  "Ducks can adapt to urban environments.",
  "Ducks' eggs hatch in spring.",
  "Ducks' plumage changes with seasons.",
  "Ducks play in water joyfully.",
  "Ducks' flocks create mesmerizing patterns.",
  "Ducks can be very protective.",
  "Ducks' feeding habits help ecosystems.",
  "Ducks' colorful feathers attract mates.",
  "Ducks' habitats are being preserved.",
  "Ducks' swimming looks effortless.",
  "Ducks' presence indicates healthy water.",
  "Ducks' interactions are fascinating to watch.",
  "Ducks' migration is a natural wonder.",
  "Ducks' calls vary by situation.",
  "Ducks' behavior is well documented.",
  "Ducks are essential to nature.",
];
